apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sonarqube
  namespace: myargo
spec:
  generators:
    - list:
        elements:
          - env: dev
            test: test1
  template:
    metadata:
      name: 'sonarqube'
      namespace: myargo
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: code
      source:
        chart: charts/sonarqube
        repoURL: https://github.com/SonarSource/helm-chart-sonarqube.git
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: code
